apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
              - app: manyconfigmap
                arg: fuga2
              - app: manysecret
                arg: fuga2
              - app: manyrole
                arg: fuga2
              - app: manyclusterrole
                arg: fuga2
          - list:
              elements:
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls1
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls2
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls3
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls4
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls5
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls6
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls7
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls8
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls9
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls10
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls11
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls12
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls13
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls14
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls15
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls16
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls17
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls18
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls19
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls20
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls21
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls22
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls23
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls24
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls25
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls26
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls27
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls28
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls29
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls30
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls31
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls32
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls33
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls34
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls35
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls36
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls37
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls38
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls39
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls40
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls41
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls42
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls43
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls44
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls45
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls46
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls47
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls48
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls49
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls50
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls51
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls52
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls53
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls54
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls55
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls56
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls57
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls58
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls59
              - cluster: local
                url: https://kubernetes.default.svc
                clustername: cls60
  template:
    metadata:
      name: '{{ clustername }}-{{ app }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: default
      source:
        repoURL: https://github.com/MasayaAoyama/argocd-test-repo
        targetRevision: 'main'
        path: '{{ app }}'
        helm:
          parameters:
          - name: app
            value: '{{ app }}'
          - name: clustername
            value: '{{ clustername }}'
          - name: arg
            value: '{{ arg }}'
          - name: suffix
            value: 'suffix'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ clustername }}'
      syncPolicy:
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
        # retry time is 15 minutes for creating cluster
        retry:
          limit: 90
          backoff:
            duration: 5s
            maxDuration: 10s
