{{- range $i, $param1 := .Values.params1 }}
{{- range $j, $param2 := $.Values.params2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $param1 }}-{{ $param2 }}-{{ $.Values.suffix }}"
stringData:
  param1: "{{ $param1 }}"
  param2: "{{ $param2 }}"
  arg: "{{ $.Values.arg }}"
  combine: "{{ $param1 }}-{{ $param2 }}-{{ $.Values.arg }}"
  app: "{{ $.Values.app }}"
  clustername: "{{ $.Values.clustername }}"
  fuga: hoge2
{{- end }}
{{- end }}
