{{- range $i, $param1 := .Values.params1 }}
{{- range $j, $param2 := $.Values.params2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ $param1 }}-{{ $param2 }}-{{ $.Values.suffix }}"
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
  resourceNmaes:
  - {{ $param1 }}
  - {{ $param2 }}
  - {{ $.Values.app }}
  - {{ $.Values.clustername }}
  - {{ $.Values.arg }}
{{- end }}
{{- end }}
